<?php

declare(strict_types=1);

namespace App\Domain\Identity;

use App\Domain\Identity\Exception\InvalidUserIdException;
use App\Domain\Shared\Tenancy\TenantId;

/**
 * A User's stable, opaque identifier (ADR-0008) — mirrors
 * {@see TenantId} exactly, for the identical
 * reason: an opaque identifier is always supplied by the caller, never
 * self-generated by this Value Object. ADR-0008 resolves where a fresh
 * value comes from for this specific identifier — the registration
 * endpoint mints a UUID v4 — but that generation decision belongs to
 * the Interfaces layer, not here.
 */
final class UserId
{
    private const MAX_LENGTH = 64;

    private const CONTROL_CHARACTER_PATTERN = '/[\x00-\x1F\x7F]/';

    private readonly string $value;

    private function __construct(string $value)
    {
        $this->value = $value;
    }

    /**
     * @throws InvalidUserIdException if the value is not a canonical
     *                                User identifier.
     */
    public static function of(string $value): self
    {
        if ($value === '' || strlen($value) > self::MAX_LENGTH) {
            throw InvalidUserIdException::forValue($value);
        }

        if (trim($value) !== $value) {
            throw InvalidUserIdException::forValue($value);
        }

        if (preg_match(self::CONTROL_CHARACTER_PATTERN, $value) === 1) {
            throw InvalidUserIdException::forValue($value);
        }

        return new self($value);
    }

    public function toString(): string
    {
        return $this->value;
    }

    public function equals(self $other): bool
    {
        return $this->value === $other->value;
    }
}
