<?php

declare(strict_types=1);

namespace App\Domain\Accounting\Period;

use App\Domain\Accounting\ChartOfAccounts\AccountId;
use App\Domain\Accounting\Journal\JournalId;
use App\Domain\Accounting\Posting\ActorReference;
use App\Domain\Accounting\Posting\IdempotencyKey;
use App\Domain\Shared\Tenancy\TenantId;
use App\Domain\Transactions\Expense\RecordExpenseCommand;

/**
 * A request to close a Tenant's books through a given date (AETS-014):
 * every Revenue and Expense Account is rolled into the given Retained
 * Earnings (Equity) Account, and no ordinary Posting Command may carry
 * a Financial Date on or before `$closedThroughDate` afterward.
 *
 * **Accounting Core, not Transactions** — deliberately distinct from
 * {@see RecordExpenseCommand}'s own
 * placement. Closing the books is a ledger-lifecycle operation every
 * Tenant needs regardless of which business-transaction types (M7
 * Expense, M9 Income, or any future one) produced the Journals being
 * closed — it is not itself a business transaction type.
 *
 * **The caller supplies the closing Journal's own identity**, mirroring
 * every other Posting Command producer in this codebase (AETS-007
 * §11): an opaque identifier is always supplied by the caller, never
 * self-generated by a Domain class.
 *
 * Pure data carrier — construction-level only. It performs no I/O,
 * validates no Account type/eligibility, and decides nothing about
 * idempotency, the previous watermark, or persistence — every one of
 * those is {@see RetainedEarningsAccountTypeValidator}'s and
 * {@see PeriodClosingService}'s job.
 */
final class PeriodClosingCommand
{
    public function __construct(
        private readonly TenantId $tenantId,
        private readonly IdempotencyKey $idempotencyKey,
        private readonly ActorReference $actor,
        private readonly JournalId $closingJournalId,
        private readonly \DateTimeImmutable $closedThroughDate,
        private readonly AccountId $retainedEarningsAccountId,
    ) {}

    public function tenantId(): TenantId
    {
        return $this->tenantId;
    }

    public function idempotencyKey(): IdempotencyKey
    {
        return $this->idempotencyKey;
    }

    public function actor(): ActorReference
    {
        return $this->actor;
    }

    public function closingJournalId(): JournalId
    {
        return $this->closingJournalId;
    }

    public function closedThroughDate(): \DateTimeImmutable
    {
        return $this->closedThroughDate;
    }

    public function retainedEarningsAccountId(): AccountId
    {
        return $this->retainedEarningsAccountId;
    }
}
