<!--
    Shared minimal PDF layout for Profit & Loss and Balance Sheet
    (AETS-009 §21, "loan-ready" export) — one template for both, the
    same reasoning AETS-017 §4 already established for Invoice and
    Quotation: they differ only in section labels and figures this
    view already parameterizes ($sections, $summaryLines), never the
    layout itself.

    No company logo, no letterhead (same Founder-level branding
    deferral as AETS-017 §3). Every value is already-computed,
    already-trusted server data (BusinessProfile, the report's own
    Query result) — never raw user HTML.

    ASCII-only in the rendered HTML below (outside this comment) —
    see document.blade.php's own identical warning: Dompdf's base
    Helvetica font silently mojibakes an em-dash/middle-dot instead of
    throwing, caught only by visually rendering a real downloaded PDF.
-->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
    body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #1a1a1a; margin: 0; padding: 32px; }
    .header { margin-bottom: 20px; }
    .business-name { font-size: 16px; font-weight: bold; margin-bottom: 4px; }
    .muted { color: #666; }
    .statement-title { font-size: 18px; font-weight: bold; letter-spacing: 0.5px; margin-top: 16px; }
    .statement-period { color: #666; margin-top: 2px; margin-bottom: 20px; }
    table.section { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
    table.section th { text-align: left; border-bottom: 1.5px solid #1a1a1a; padding: 5px 4px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
    table.section th.num, table.section td.num { text-align: right; }
    table.section td { padding: 4px; border-bottom: 1px solid #eee; }
    tr.subtotal td { border-top: 1px solid #1a1a1a; border-bottom: none; font-weight: bold; padding-top: 6px; }
    .summary { display: table; width: 100%; margin-top: 20px; border-top: 2px solid #1a1a1a; padding-top: 10px; }
    .summary-row { display: table; width: 100%; padding: 3px 0; }
    .summary-row .label { display: table-cell; width: 70%; }
    .summary-row .amount { display: table-cell; width: 30%; text-align: right; }
    .summary-row.emphasized { font-size: 14px; font-weight: bold; }
    .footer { margin-top: 32px; font-size: 9px; color: #999; }
</style>
</head>
<body>
    <div class="header">
        <div class="business-name">{{ $seller['legal_name'] }}</div>
        @foreach ($seller['address_lines'] as $line)
            <div class="muted">{{ $line }}</div>
        @endforeach
        @if ($seller['registration_number'])
            <div class="muted">Reg. No: {{ $seller['registration_number'] }}</div>
        @endif

        <div class="statement-title">{{ $statementTitle }}</div>
        <div class="statement-period">{{ $periodLabel }} - Amounts in {{ $currency }}</div>
    </div>

    @foreach ($sections as $section)
        <table class="section">
            <thead>
                <tr>
                    <th>{{ $section['label'] }}</th>
                    <th class="num">Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($section['lines'] as $line)
                    <tr>
                        <td>{{ $line['name'] }}</td>
                        <td class="num">{{ $line['amount'] }}</td>
                    </tr>
                @endforeach
                <tr class="subtotal">
                    <td>Total {{ $section['label'] }}</td>
                    <td class="num">{{ $section['subtotal'] }}</td>
                </tr>
            </tbody>
        </table>
    @endforeach

    <div class="summary">
        @foreach ($summaryLines as $line)
            <div class="summary-row {{ $line['emphasized'] ? 'emphasized' : '' }}">
                <div class="label">{{ $line['label'] }}</div>
                <div class="amount">{{ $currency }} {{ $line['amount'] }}</div>
            </div>
        @endforeach
    </div>

    <div class="footer">
        Generated by hore.my - a computer-generated statement, no signature required. Compliance-ready
        (organised, consistent, traceable) does not itself guarantee acceptance by any bank, auditor, or authority.
    </div>
</body>
</html>
