<!--
    Shared minimal PDF layout for a flat, row-per-record report — Trial
    Balance, General Ledger, Aging Report, and Evidence Index (AETS-009
    §21, extended v1.9.0) — the same "one template, parameterized"
    reasoning §21 already established for financial-statement.blade.php
    (Profit & Loss / Balance Sheet / Cash Flow) and AETS-017 §4 for
    Invoice/Quotation: these four differ only in column headers, row
    cells, and optional note/summary lines this view already
    parameterizes ($columns, $rows, $noteLines, $summaryLines), never
    the layout itself. None of the four is a subtotaled-sections
    "statement" the way P&L/Balance Sheet/Cash Flow are — each is a
    flat list of records, structurally closer to document.blade.php's
    own line-item table than to financial-statement.blade.php's
    sectioned one.

    No company logo, no letterhead (same Founder-level branding
    deferral as AETS-017 §3). Every value is already-computed,
    already-trusted server data — never raw user HTML.

    ASCII-only in the rendered HTML below (outside this comment) — see
    document.blade.php's own identical warning: Dompdf's base Helvetica
    font silently mojibakes an em-dash/middle-dot instead of throwing,
    caught only by visually rendering a real downloaded PDF.
-->
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<style>
    body { font-family: Helvetica, Arial, sans-serif; font-size: 11px; color: #1a1a1a; margin: 0; padding: 32px; }
    .header { margin-bottom: 20px; }
    .business-name { font-size: 16px; font-weight: bold; margin-bottom: 4px; }
    .muted { color: #666; }
    .report-title { font-size: 18px; font-weight: bold; letter-spacing: 0.5px; margin-top: 16px; }
    .report-period { color: #666; margin-top: 2px; margin-bottom: 20px; }
    table.rows { width: 100%; border-collapse: collapse; margin-bottom: 14px; }
    table.rows th { text-align: left; border-bottom: 1.5px solid #1a1a1a; padding: 5px 4px; font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; }
    table.rows th.num, table.rows td.num { text-align: right; }
    table.rows td { padding: 4px; border-bottom: 1px solid #eee; }
    .notes { margin: 4px 0 14px; }
    .notes p { margin: 2px 0; color: #444; }
    .summary { display: table; width: 100%; margin-top: 10px; border-top: 2px solid #1a1a1a; padding-top: 10px; }
    .summary-row { display: table; width: 100%; padding: 3px 0; }
    .summary-row .label { display: table-cell; width: 70%; }
    .summary-row .amount { display: table-cell; width: 30%; text-align: right; }
    .summary-row.emphasized { font-size: 14px; font-weight: bold; }
    .footer { margin-top: 32px; font-size: 9px; color: #999; }
</style>
</head>
<body>
    <div class="header">
        <div class="business-name">{{ $seller['legal_name'] }}</div>
        @foreach ($seller['address_lines'] as $line)
            <div class="muted">{{ $line }}</div>
        @endforeach
        @if ($seller['registration_number'])
            <div class="muted">Reg. No: {{ $seller['registration_number'] }}</div>
        @endif

        <div class="report-title">{{ $reportTitle }}</div>
        <div class="report-period">{{ $periodLabel }}</div>
    </div>

    <table class="rows">
        <thead>
            <tr>
                @foreach ($columns as $column)
                    <th class="{{ $column['align'] === 'right' ? 'num' : '' }}">{{ $column['label'] }}</th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach ($rows as $row)
                <tr>
                    @foreach ($row as $index => $cell)
                        <td class="{{ $columns[$index]['align'] === 'right' ? 'num' : '' }}">{{ $cell }}</td>
                    @endforeach
                </tr>
            @endforeach
            @if (empty($rows))
                <tr>
                    <td colspan="{{ count($columns) }}" class="muted">No records for this period.</td>
                </tr>
            @endif
        </tbody>
    </table>

    @if (!empty($noteLines))
        <div class="notes">
            @foreach ($noteLines as $note)
                <p>{{ $note }}</p>
            @endforeach
        </div>
    @endif

    @if (!empty($summaryLines))
        <div class="summary">
            @foreach ($summaryLines as $line)
                <div class="summary-row {{ $line['emphasized'] ? 'emphasized' : '' }}">
                    <div class="label">{{ $line['label'] }}</div>
                    <div class="amount">{{ $line['amount'] }}</div>
                </div>
            @endforeach
        </div>
    @endif

    <div class="footer">
        Generated by hore.my - a computer-generated report, no signature required. Compliance-ready
        (organised, consistent, traceable) does not itself guarantee acceptance by any bank, auditor, or authority.
    </div>
</body>
</html>
